const API_KEY = process.env.SHOPIFY_API_KEY;
const API_SECRET_KEY = process.env.SHOPIFY_API_SECRET_KEY;
const SHOPIFY_SHOP = process.env.SHOPIFY_SHOPIFY_SHOP;
const ADMIN_ACCESS_TOKEN = process.env.SHOPIFY_ADMIN_ACCESS_TOKEN;

const STOREFRONT_API_KEY = process.env.SHOPIFY_STOREFRONT_API_KEY;
const STOREFRONT_API_SECRET_KEY = process.env.SHOPIFY_STOREFRONT_API_SECRET_KEY;
const STOREFRONT_ACCESS_TOKEN = process.env.SHOPIFY_STOREFRONT_ACCESS_TOKEN;

export { API_KEY, API_SECRET_KEY, SHOPIFY_SHOP, ADMIN_ACCESS_TOKEN, STOREFRONT_API_KEY, STOREFRONT_API_SECRET_KEY, STOREFRONT_ACCESS_TOKEN }