const TWILIO_SID = process.env.TWILIO_SID;
const TWILIO_TOKEN = process.env.TWILIO_TOKEN;
const TWILIO_MESSAGING_SERVICE_ID = process.env.TWILIO_MESSAGING_SERVICE_ID;

export { TWILIO_SID, TWILIO_TOKEN, TWILIO_MESSAGING_SERVICE_ID }